POST http://localhost:3001/v1/auth/login
Content-Type: application/json

{
  "username": "martin.luz",
  "password": "martin.1234"
}

###
GET http://localhost:3001/v1/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjU3ZTlmODE4NWE0MmNjYjIwODUyNiIsInVzZXJuYW1lIjoibWFydGluLmx1eiIsImlhdCI6MTc0NDk3OTYxMywiZXhwIjoxNzQ0OTgzMjEzfQ.oyKCK3kPCZATmlZvFZOn59yNPexZxhhzMd1JJ6aIA-M
Content-Type: application/json
